name: temp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.3
  shared_preferences: ^2.0.20
  file_picker: ^8.0.0+1
  http: ^1.2.1
  dio: ^5.4.2+1
  future_progress_dialog: ^0.2.0
<<<<<<< Updated upstream
=======
  uuid: ^4.4.0
  fluttertoast: ^8.2.6
  flutter_slidable: ^3.1.0
  image_picker: ^1.1.2

>>>>>>> Stashed changes
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/